# List of player attributes
STRENGTH_ATTR = "Strength"
DEXTERITY_ATTR = "Dexterity"
STAMINA_ATTR = "Stamina"
INTELLIGENCE_ATTR = "Intelligence"
WISDOM_ATTR = "Wisdom"
NOBILITY_ATTR = "Nobility"
PERCEPTION_ATTR = "Perception"
LUCK_ATTR = "Luck"
CHARISMA_ATTR = "Charisma"
LEADERSHIP_ATTR = "Leadership"
PIETY_ATTR = "Piety"
STEALTH_ATTR = "Stealth"

PLAYER_ATTRIBUTES = [STRENGTH_ATTR, DEXTERITY_ATTR, STAMINA_ATTR,
                     INTELLIGENCE_ATTR, WISDOM_ATTR, NOBILITY_ATTR,
                     PERCEPTION_ATTR, LUCK_ATTR, CHARISMA_ATTR,
                     LEADERSHIP_ATTR, PIETY_ATTR, STEALTH_ATTR]

